### ISSUE TITLE
Stuck at step 4 - Add label name to your pod on the pipeline

### ISSUE THREAD

**Issue by Zerberuss** [mike0355/k8s-facenet-distributed-training#1]
A description with more details is needed what you have to do with the config shown in Figure5.
Also the handling of the config shown in Figure8 should be described further. 

Thank you very much for your detailed how-to!

**Comment by mike0355** [comment]
In the service.yaml,we need to use selector to select the pod to open the port , that's why we need to define the label name in the pipeline in Figure.5 

In figure.8 ,We have to add tag to each node first, k8s have command to add tag.
And after add tag,  we need to define the parameter for node selector, this allows users to specify the pod to be deployed under the node with the specified tag.

**Comment by Zerberuss** [comment]
Thank you!
